version: 2
updates:
  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    reviewers:
      - "Drmcoelho"
    labels:
      - "dependencies"
      - "security"
    commit-message:
      prefix: "chore(deps)"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    reviewers:
      - "Drmcoelho"
    labels:
      - "dependencies"
      - "ci/cd"
    commit-message:
      prefix: "chore(deps)"

  # npm/pnpm dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    reviewers:
      - "Drmcoelho"
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore(deps)"
