[project]
name = "mega-content-engine"
version = "0.1.0"
description = "Content engine for PDF ingestion and indexing"
requires-python = ">=3.11"
dependencies = ["PyPDF2"]

[tool.setuptools.packages.find]
where = ["src"]

[build-system]
requires = ["setuptools>=68.0", "wheel"]
build-backend = "setuptools.build_meta"
