name: ✨ Feature Request
description: Sugerir uma nova funcionalidade
title: "[FEATURE] "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Obrigado por sugerir uma nova funcionalidade!

  - type: textarea
    id: problem
    attributes:
      label: Problema ou Necessidade
      description: Qual problema esta feature resolve?
      placeholder: Eu sempre fico frustrado quando...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Solução Proposta
      description: Descreva a solução que você gostaria
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternativas Consideradas
      description: Descreva alternativas que você considerou

  - type: textarea
    id: additional
    attributes:
      label: Contexto Adicional
      description: Adicione qualquer outro contexto ou screenshots
