[project]
name = "mega-multi-agent"
version = "0.1.0"
description = "Sistema multi-agente pedagógico (skeleton)"
authors = [{name="MEGA"}]
requires-python = ">=3.11"

[tool.setuptools.packages.find]
where=["src"]
[build-system]
requires = ["setuptools>=68.0", "wheel"]
build-backend = "setuptools.build_meta"
