[project]
name = "mega-common-utils"
version = "0.1.0"
description = "Utilidades compartilhadas (config, logging)"
requires-python = ">=3.11"

[tool.setuptools.packages.find]
where=["src"]
[build-system]
requires = ["setuptools>=68.0", "wheel"]
build-backend = "setuptools.build_meta"
