[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "mega-cli"
version = "0.1.0"
description = "MEGA CLI - Command line interface for Medical Education with Generative AI"
readme = "README.md"
requires-python = ">=3.8"
authors = [
    {name = "MEGA Team"},
]
dependencies = [
    "typer[all]>=0.9.0",
    "pyyaml>=6.0",
    "rich>=13.0.0",
]

[project.scripts]
mega = "mega_cli.main:app"

[tool.hatch.build.targets.wheel]
packages = ["src/mega_cli"]