[project]
name = "mega-adaptive"
version = "0.1.0"
description = "Adaptive learning engine (skeleton)"
authors = [{ name = "MEGA" }]
requires-python = ">=3.11"

[tool.setuptools.packages.find]
where = ["src"]