#!/bin/sh

# Run lint, format, and type-check for the frontend
echo "Running frontend checks..."
pnpm --filter mega-frontend lint
pnpm --filter mega-frontend format
pnpm --filter mega-frontend type-check

# Run lint, format, and type-check for the python packages
echo "Running python checks..."
source venv/bin/activate
pnpm lint:py
pnpm format:py
pnpm type-check:py

for file in $(git diff --cached --name-only --diff-filter=ACM); do
  if [ -f "$file" ]; then
    size=$(stat -f%z "$file")
    if [ "$size" -gt $((100 * 1024 * 1024)) ]; then
      echo "ERRO: Arquivo \"$file\" possui $(($size/1024/1024)) MB (>100MB). Commit abortado."
      exit 1
    fi
  fi
done