#!/bin/sh
for file in $(git diff --cached --name-only --diff-filter=ACM); do
  if [ -f "$file" ]; then
    size=$(stat -f%z "$file")
    if [ "$size" -gt $((100 * 1024 * 1024)) ]; then
      echo "ERRO: Arquivo \"$file\" possui $(($size/1024/1024)) MB (>100MB). Commit abortado."
      exit 1
    fi
  fi
done