name: Validate Manifests

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'content/modules/**'
      - 'scripts/validate_manifests.py'
      - '.github/workflows/validate-manifests.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'content/modules/**'
      - 'scripts/validate_manifests.py'
      - '.github/workflows/validate-manifests.yml'

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pydantic pyyaml
    
    - name: Validate manifests
      run: |
        python3 scripts/validate_manifests.py
    
    - name: Run manifest validation tests
      run: |
        pip install pytest
        pytest tests/test_manifest_validation.py -v
